"""my_tool — single-file Maya tool template with Update-from-GitHub.

Everything the tool needs lives here:
    * __version__ for install.py's before/after dialog and the UI footer
    * show() to open the tool window
    * The Update-from-GitHub button flow (evalDeferred 3-stage, safe
      window teardown, SHA-pinned re-fetch of install.py)

Ship this file + install.py — that's it. Add your real controls and
tool logic in place of the placeholder ``_build_body``.

Shelf button command (auto-generated by install.py) is just:

    import my_tool; my_tool.show()

Rename the module to whatever your tool is (``paint_projectile``,
``rig_utils``, etc.) — remember to update install.py's ``_PACKAGE`` to
match.
"""

from __future__ import annotations

try:
    from maya import cmds  # type: ignore
except ImportError:  # pragma: no cover
    cmds = None  # type: ignore


__version__ = "0.1.0"


WINDOW = "myToolWin"  # match install.py's _close_existing_window() target

# ─── CUSTOMIZE ────────────────────────────────────────────────────────────
_GITHUB_OWNER = "YOUR_GITHUB_USERNAME"
_GITHUB_REPO = "YOUR_REPO_NAME"
_GITHUB_BRANCH = "main"
_PACKAGE = "my_tool"          # matches this file's module name
# ─── END CUSTOMIZE ────────────────────────────────────────────────────────

_GITHUB_API = f"https://api.github.com/repos/{_GITHUB_OWNER}/{_GITHUB_REPO}"
_GITHUB_RAW_BASE = f"https://raw.githubusercontent.com/{_GITHUB_OWNER}/{_GITHUB_REPO}"


# --------------------------------------------------------------------------- #
# Update-from-GitHub flow  (patterns doc §1-7, §1-8, §1-9)
# --------------------------------------------------------------------------- #

def _resolve_latest_sha() -> str:
    """SHA-pinned URLs are the only reliable cache-buster for
    raw.githubusercontent.com. Ask the API for main's tip commit."""
    import json
    import random
    import time
    import urllib.request

    salt = f"{time.time():.6f}_{random.randint(0, 2 ** 32)}"
    req = urllib.request.Request(
        f"{_GITHUB_API}/branches/{_GITHUB_BRANCH}?_={salt}",
        headers={
            "Accept": "application/vnd.github+json",
            "Cache-Control": "no-cache",
            "User-Agent": f"{_PACKAGE}-updater/{salt}",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))["commit"]["sha"]
    except Exception as exc:
        print(f"[{_PACKAGE}] SHA lookup failed ({exc}); falling back to "
              f"{_GITHUB_BRANCH}")
        return _GITHUB_BRANCH


def update_from_github(*_args) -> None:
    """UI button callback. Immediately returns — the actual work runs
    on the next Maya idle so we don't tear down the window that owns
    this callback while the callback is still on the stack."""
    cmds.evalDeferred(_run_update, lowestPriority=True)


def _run_update() -> None:
    import sys
    import traceback
    import urllib.request

    sha = _resolve_latest_sha()
    url = f"{_GITHUB_RAW_BASE}/{sha}/install.py"
    print(f"[{_PACKAGE}] update: fetching {url}")
    try:
        req = urllib.request.Request(url, headers={
            "Cache-Control": "no-cache",
            "User-Agent": f"{_PACKAGE}-updater/{sha[:10]}",
        })
        source = urllib.request.urlopen(req, timeout=30).read()
    except Exception as exc:
        traceback.print_exc()
        cmds.confirmDialog(title="Update failed",
                           message=f"install.py fetch failed:\n{exc}",
                           button=["OK"])
        return

    if cmds.window(WINDOW, exists=True):
        try:
            cmds.deleteUI(WINDOW)
        except Exception:
            pass

    ns = {"__name__": "install", "__file__": "<github>"}
    try:
        exec(compile(source, "install.py (from GitHub)", "exec"), ns)
    except Exception as exc:
        traceback.print_exc()
        cmds.confirmDialog(
            title="Update failed",
            message=(f"install.py raised:\n{type(exc).__name__}: {exc}\n\n"
                     "See Script Editor for full traceback."),
            button=["OK"])
        return

    # Flush self so the next `import my_tool` re-reads the fresh copy.
    for m in [k for k in list(sys.modules) if k == _PACKAGE]:
        sys.modules.pop(m, None)

    # Defer reopen so install()'s modal is fully dismissed first.
    cmds.evalDeferred(_reopen_after_update, lowestPriority=True)


def _reopen_after_update() -> None:
    import importlib
    import sys
    import traceback
    try:
        if _PACKAGE in sys.modules:
            importlib.reload(sys.modules[_PACKAGE])
        mod = importlib.import_module(_PACKAGE)
        mod.show()
    except Exception as exc:
        traceback.print_exc()
        cmds.confirmDialog(
            title="Reopen failed",
            message=(f"Update finished but reopening the tool window "
                     f"failed:\n{type(exc).__name__}: {exc}\n\n"
                     "Click the shelf button to reopen manually."),
            button=["OK"])


# --------------------------------------------------------------------------- #
# Window  — replace _build_body with your real controls
# --------------------------------------------------------------------------- #

def _build_body() -> None:
    """Placeholder tool UI. Replace with your real controls."""
    cmds.separator(h=4, style="none")
    cmds.text(l="このウィンドウ本体は自由に組み替えて OK。",
              al="left")
    cmds.text(l="下の「GitHub から更新」だけそのまま置いておけば\n"
                "アップデートフローは動きます。",
              al="left")


def show() -> str:
    if cmds is None:
        raise RuntimeError("show() must be called inside Maya.")

    if cmds.window(WINDOW, exists=True):
        cmds.deleteUI(WINDOW)

    win = cmds.window(WINDOW,
                      t=f"My Tool  —  v{__version__}",
                      w=340, h=200, mnb=True, mxb=False, s=True)
    cmds.columnLayout(adj=True, rs=8, cat=("both", 10))

    _build_body()

    cmds.separator(h=10, style="in")
    cmds.rowLayout(nc=2, adj=1, cw2=(200, 130))
    cmds.text(l=f"{_PACKAGE}  v{__version__}",
              al="left", fn="smallObliqueLabelFont")
    cmds.button(l="GitHub から更新", h=24, c=update_from_github)
    cmds.setParent("..")

    cmds.showWindow(win)
    return win
